---
apiVersion: v1
kind: Service
metadata:
  name: hackaton-fin-department
  namespace: hackaton-fin
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: hackaton-fin-department
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hackaton-fin-department
  namespace: hackaton-fin
spec:
  hosts:
    - "${APP_HOST}"
  gateways:
    - istio-system/fin-gw
  http:
    - name: primary
      route:
        - destination:
            host: hackaton-fin-department.hackaton-fin.svc.cluster.local
            port:
              number: 80
      timeout: 60s
