# Root creds MinIO. Vault: secret/data/minio/root {rootUser, rootPassword}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-root
  namespace: minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio-root
    creationPolicy: Owner
  data:
    - secretKey: rootUser
      remoteRef:
        key: minio/root
        property: rootUser
    - secretKey: rootPassword
      remoteRef:
        key: minio/root
        property: rootPassword
