---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio
resources:
  - namespace.yaml
  - external-secret.yaml
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - istio.yaml
  - cnpg-backup-bucket-job.yaml
  - loki-bucket-job.yaml
