---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-pg
  namespace: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-pg
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: ${HARBOR_DB_USER}
        password: "{{ .password }}"
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: database/harbor
        property: password
