apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Всё в flux-system: image-контроллеры работают в связке с GitRepository
# flux-system, туда же кладём robot-секрет Harbor.
namespace: flux-system
resources:
  - image-policy.yaml
  - image-automation.yaml
  - harbor-registry.yaml
