apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jetstack.yaml
  - istio.yaml
  - weave-gitops.yaml
  - hashicorp.yaml
  - external-secrets.yaml
  - metallb.yaml
  - cloudnative-pg.yaml
  - harbor.yaml
  - prometheus-community.yaml
  - grafana.yaml
  - headlamp.yaml
  - longhorn.yaml
  - open-telemetry.yaml
  - jaeger.yaml
