---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/weaveworks/weave-gitops
  ref:
    tag: v0.38.0
